variables: &go-variables
  GOFLAGS: "-mod=vendor -tags=jsoniter"
  GOPRIVATE: "gitlab.wheniwork.com"

.login-go:
  before_script:
    # ssh agent
    - mkdir -p /root/.ssh
    - cp /auth/id_rsa* /root/.ssh
    - chmod 600 /root/.ssh/*
    - eval $(ssh-agent)
    - ssh-add /root/.ssh/id_rsa
    - cp _common/ci/gitconfig /root/.gitconfig
    - export PATH=$PATH:$GOPATH/bin
    - go version
    - go env

stages:
  - test

# golang unit tests
test:
  stage: test
  tags:
    - k8s-build
  image: nexus-docker-out.build-tools.wheniwork-production.com/containers/build-go:1.22-bullseye-master
  extends: .login-go
  variables:
    <<: *go-variables
  script:
    - GO111MODULE=on GOFLAGS="" go install github.com/jstemmer/go-junit-report@latest
    - GO111MODULE=on GOFLAGS="" go install github.com/t-yuki/gocover-cobertura@latest
    - go mod vendor
    - go vet ./...
    # Run tests with combined coverage
    - ./_common/ci/coverage.sh
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
      - vendor/
  artifacts:
    expire_in: 7 days
    paths:
      - report.xml
      - coverage.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml
